services:
  postgres: 
    image: postgres:16
    container_name: rent_postgres
    environment: 
      POSTGRES_DB: rent
      POSTGRES_USER: rent
      POSTGRES_PASSWORD: rent
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: rent_redis
    ports: 
      - "6379:6379"
    
volumes:
  pgdata: 